version: '3.1'
services:
    web:
        image: dcdemo/docker-pets:latest
        ports:
            - 5000:5000
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3 